
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xdd\x06=\x87s\x9d\xe2p\xdc1\xd2\x92\xc7\xaaI\xc7'
    
_lr_action_items = {'AND':([1,2,5,6,8,10,11,],[-3,-6,9,-5,-7,-4,-2,]),'$end':([1,2,4,5,6,8,10,11,],[-3,-6,0,-1,-5,-7,-4,-2,]),'ANNOTATION':([0,3,7,9,],[2,8,2,2,]),'REL':([0,7,9,],[3,3,3,]),'OR':([1,2,6,8,10,11,],[7,-6,-5,-7,-4,7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[4,]),'andquery':([0,],[5,]),'orquery':([0,9,],[1,11,]),'unitquery':([0,7,9,],[6,10,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> andquery','query',1,'p_query_main','ply_masterclass.py',53),
  ('andquery -> andquery AND orquery','andquery',3,'p_andquery_and','ply_masterclass.py',58),
  ('andquery -> orquery','andquery',1,'p_andquery_or','ply_masterclass.py',63),
  ('orquery -> orquery OR unitquery','orquery',3,'p_orquery_or','ply_masterclass.py',68),
  ('orquery -> unitquery','orquery',1,'p_orquery_unit','ply_masterclass.py',73),
  ('unitquery -> ANNOTATION','unitquery',1,'p_unitquery_annot','ply_masterclass.py',78),
  ('unitquery -> REL ANNOTATION','unitquery',2,'p_unitquery_rel','ply_masterclass.py',83),
]
